name: Ubuntu

on:
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Visit https://remotedesktop.google.com/headless & paste the authorization code'
        required: true
      pincode:
        description: 'Enter a pin code'
        default: '123456'
        required: true
      authtoken:
        description: 'NGROK_AUTH_TOKEN'
        required: true
      computername:
        description: 'MACHINE_NAME'
        default: 'ubuntu'
        required: true
      username:
        description: 'USER_NAME'
        default: 'user'
        required: true
      password:
        description: 'USER_PASSWORD'
        default: 'root'
        required: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Mask Code & Pin
      run: |
        _Token=$(jq -r '.inputs.authtoken' $GITHUB_EVENT_PATH)
        _CName=$(jq -r '.inputs.computername' $GITHUB_EVENT_PATH)
        _Pass=$(jq -r '.inputs.password' $GITHUB_EVENT_PATH)
        echo ::add-mask::$_Token
        echo ::add-mask::$_CName
        echo ::add-mask::$_Pass
        echo NGROK_TOKEN="$_Token" >> $GITHUB_ENV
        echo ComputerName="$_CName" >> $GITHUB_ENV
        echo Password="$_Pass" >> $GITHUB_ENV
    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get upgrade
    - name: Installing Desktop Environment
      run: sudo bash Ubuntu.sh
    - name: Setting up Ngrok
      run:  bash Setup.sh "${{ env.NGROK_TOKEN }}" "${{ env.ComputerName }}" "${{ github.event.inputs.username }}" "${{ env.Password }}"
    - name: Starting Chrome Remote Desktop
      run: DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AVMBsJg02sBu24HBpZwq4mVr_rT0P9BP2ANvCa1gJrGzsI44nlKtkovRtlGMhSNvFqzpsQ" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)
    - name: IP for Connect to your SSH
      run: bash Ip.sh "${{ github.event.inputs.username }}"
    - name: Keep Alive
      run: ping 127.0.0.1 > null
